### ISSUE TITLE
How to convert a Reaction / Trasformation column into Smile/Smart

### ISSUE THREAD

**Issue by HiteSit** [thsa/datawarrior#21]
Hello Everyone,

I'm curious to know if it's possible to convert a column of reactions or transformations into its equivalent SMILES format, similar to how it's done for a molecule column. Specifically, I aim to generate a text file where each entry in the Reaction/Transformation column is represented not by its proprietary rxncode, but by the actual SMILES representation (e.g. 'Oc1ccccc1.O=C(c1ccccc1)Cl>>O=C(c1ccccc1)c1ccccc1'). I know this is feasible on an individual basis by selecting a datapoint and using the 'copy from reaction > reaction as > reaction-SMILES' option. Therefore, I'm wondering if there's a way to automatically perform this conversion for every entry in a column while also creating a new column with these SMILES representations, similar to the process for extracting SMILES from a reaction column.

**Comment by nbehrnd** [comment]
This task is very much possible.  As for a demonstration, I set up a combinatorial library (Chemistry -> Enumerate Combinatorial Library), used the reaction template of the Diels-Alder reaction for 10 dienes and dienophiles each to generate attached `Diels-Alder.dwar`.

Next, assign SMILES strings to the two reactants and the products.  That is Chemistry -> From Chemical Structure -> Add SMILES code for each of them to generate and populate three new columns.  Then, it is time to concatenate the strings.  This equally is a task DataWarrior can do for you by Data -> Add Calculated Values with a formula of

```
Smiles_reactant01+ "." + Smiles_reactant02 + ">>" +Smiles_product 
```

![string_concatenation](https://github.com/thsa/datawarrior/assets/19709084/ba35fc21-3a97-4f32-9b55-87c35e48b0d7)

Pay attention that no already existing column is overwritten (the lower part of the widget).  This then creates, as expected, an new column.

The assignment of SMILES to the reactants and products, as well as the concatenation of the strings can be stored in a DataWarrior macro file (`.dwam`) for documentation and reuse which the archive below equally includes: open the `Diels-Alder.dwar` file, then read the macro file (Macro -> Import Macro) and use it (Macro -> Run Macro -> construct_reaction_smiles).

What remains to do is to access the results.  I recommend you save the results as a plain text file (File -> Save Special -> Text file, tabulator separated columns) and collect the SMILES about the reaction for instance with AWK

```
$ awk '{print $NF}' Diels_Alder.txt
Smiles_reaction
C=CC(N(Cc1ccccc1)Cc1ccccc1)=O.Cc(cc1)ccc1-c1ccc(C(O)=O)[s]1>>Cc1ccc(C(CC2C(N(Cc3ccccc3)Cc3ccccc3)=O)(C=C3)SC23C(O)=O)cc1
C=CC(N(Cc1ccccc1)Cc1ccccc1)=O.Cc1cc(-c([n]2C)nnc2S)c[s]1>>CC1(CC2C(N(Cc3ccccc3)Cc3ccccc3)=O)SC2C(c([n]2C)nnc2S)=C1
C=CC(N(Cc1ccccc1)Cc1ccccc1)=O.CC=C(C)C=CC=C(C)C>>CC(CC1C(N(Cc2ccccc2)Cc2ccccc2)=O)C(C)=CC1C=C(C)C
[...]
```

which equally can be redirected into a permanent record

```shell
$ awk '{print $NF}' Diels_Alder.txt > reaction_smiles.txt
```

[2024-01-23_test_case.zip](https://github.com/thsa/datawarrior/files/14030607/2024-01-23_test_case.zip)

**Comment by thsa** [comment]
sorry for the long delay. Version 6.1.2 will have that functionality...
