### ISSUE TITLE
mmtf.jar missing in classpath under Windows

### ISSUE THREAD

**Issue by rufenerc** [thsa/datawarrior#22]
The mmtf.jar is missing in classpath of DW 5.5.0. Unlike the versions on MacOS and Linux where the classpath is provided via wildcards, the Windows executable is using a different mechanism which is lacking the reference to mmtf.jar.

**Comment by thsa** [comment]
Thanks for the hint. This Seems to be OK in current build files for msi. Was evidently fixed some time ago. For the next installer, this will run through testing...
