### ISSUE TITLE
Datawarrior fails to start on Windows if not installed in C:\Program Files\DataWarrior

### ISSUE THREAD

**Issue by rufenerc** [thsa/datawarrior#25]
Although the MSI installation allows me to install DataWarrior in a different folder then proposed, it fails to start by not finding datawarrior_all.jar in C:\Program Files DataWarrior (obviously)
Version: 6.01.00 on Windows 10

![image](https://github.com/thsa/datawarrior/assets/10071969/85d55600-3edf-42f7-bd25-54fe6c74d4c3)

**Comment by thsa** [comment]
Indeed, currently, DataWarrior needs to get installed into the default path on all platforms...
