### ISSUE TITLE
could there any script to run sar or R-Group decompostion automatically？

### ISSUE THREAD

**Issue by LingjieBao1998** [thsa/datawarrior#30]
Thank you for your open source work, the speed and accuracy are pretty good. Could there any script to run sar or R-Group decompostion automatically？

**Comment by thsa** [comment]
sure. Using macros you can automate anything in DataWarrior, including running a R-group deconvolution. Just open a macro editor, create a new macro, drag the task R-group deconvolution task into the new macro and configure it. You may add more tasks, e.g. to create views to show your outcome. An alternative to buildign a macro from scratch is to record what you do interactively. You can still change the macro afterward in the macro editor. If you put an 'exit program' task at the end of the macro, you could even run the macro from a shell script. After creating a macro, it is part of the open window, but you can export it into a dwam file and use it independently of that file, e.g. as global macro. You can also copy/paste macros quickly via the clipboard to/from a text editor to finetune them (if you know what you are doing).

**Comment by LingjieBao1998** [comment]
Thanks for lot. Could you provide some case

**Comment by thsa** [comment]
?
