### ISSUE TITLE
Structure editor no longer allows to specify multiple bond types for structure filtering

### ISSUE THREAD

**Issue by vaitkus** [thsa/datawarrior#35]
Steps to reproduce:

1. Load a test dataset, for example click "Database" -> "Retrieve Wikipedia Molecules".
2. Open the structure editor and draw a single CC bond.
3. Select the lasso tool, double click the bond and first check the "double" bond box and then also the "triple" bond box.
4. Run the filtering.

Only structures with the triple bond will be displayed in the results (304 entries in the case of Wikipedia).

Furthemore, if you go back to the structure editor and once again open the bond properties dialog, only the "triple" bond is checked.

I observed this behaviour with DataWarrior built from commit [8f54fc2](https://github.com/thsa/datawarrior/commit/8f54fc298ad3bddb54c5005b3de87055d4077a20) under Ubuntu 22.04, openjdk 21.0.4.

**Comment by thsa** [comment]
this was actually a bug in the bond query feature dialog of the editor in openchemlib. I just fixed it. The next DataWarrior update will contain the fix.

**Comment by vaitkus** [comment]
Great, thank you!
